stages:
  - update version
  - build
  - test
  - review
  - clean

variables:
  NEW_VERSION_SH: ./deploy/newVersion.sh
  DOCKER_COMPOSE_PATH: ./deploy

include: 
  - project: 'webjar/webjar-ci-cd-templates'
    file: 
      - 'run-pipeline-with-new-version-then-new-tag.yml'
      - 'docker-compose/build.yml'
      - 'docker-compose/review.yml'
      - 'docker-compose/clean.yml'