export enum groupQueryTypeEnum {
  BUSINESS_CLASSIFICATION = 'BUSINESS_CLASSIFICATION',
  ORDER_RANGE = 'ORDER_RANGE',
  PURCHASED_PRODUCT_RANGE = 'PURCHASED_PRODUCT_RANGE',
  PAID_MONEY_RANGE = 'PAID_MONEY_RANGE',
  PRODUCTS_IN_BASKET_AVERAGE = 'PRODUCTS_IN_BASKET_AVERAGE',
  PAYMENT_AVERAGE = 'PAYMENT_AVERAGE',
  HAS_FEEDBACK = 'HAS_FEEDBACK',
  NUMBER_OF_FAILED_PAYMENT = 'NUMBER_OF_FAILED_PAYMENT',
  BADGE_LABEL = 'BADGE_LABEL',
  SATISFACTION_LABEL = 'SATISFACTION_LABEL ',
}
