version: '3'

services:
  app:
    image: ${CI_REGISTRY_IMAGE:-registry.git.hermes.ir/hermes-product/hermes-admin-panel-vue}:${IMAGE_TAG}
    restart: always
    command: bash -c "npm run build && node deploy/server/server.js"
    ports:
      - '${ADMIN_CONTAINER_PORT:-3000}:${PORT:-3000}'
    networks:
      - admin_vue_network
    env_file:
      - app.env

networks:
  admin_vue_network:
    driver: bridge
